services:
  #ui-reverse-proxy:
  #  build:
  #    context: .
  #    dockerfile: docker/nginx-ui-reverse-proxy/Dockerfile
  #  ports:
  #    - 80:80
  #  depends_on:
  #    - remote-auth-ui
  #    - remote-chat-ui
  #    - host-multichat-ui

  remote-auth-ui:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=remotes/auth
        - VITE_UI_GATEWAY_URL=https://openschema-ui.elpai.org

  remote-chat-ui:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=remotes/chat
        - VITE_UI_GATEWAY_URL=https://openschema-ui.elpai.org

  host-multichat-ui:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=hosts/multichat
        - VITE_UI_GATEWAY_URL=https://openschema-ui.elpai.org

networks:
  shared-net:
    name: net
