services:
  gateway:
    build:
      context: src/service/gateway
      dockerfile: Dockerfile
      args:
        - SERVICE_DIR=hosts/multichat
    ports:
      - 80:80
      - 443:443

  host-multichat-ui:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=hosts/multichat

  remote-auth-ui:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=remotes/auth

  remote-chat-ui:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=remotes/chat

networks:
  shared-net:
    name: net
