services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/certs/cert.pem
      - ./key.pem:/etc/ssl/certs/key.pem

  # template-worker:
  #   build:
  #     context: .
  #     dockerfile: docker/python/Dockerfile.dev
  #     args:
  #       - SERVICE=template
  #   command: ["python", "worker.py"]
  #   env_file:
  #     - .env.dev
  #   environment:
  #     - SERVICE_NAME=auth
  #     - SERVICE_ID=template.service
  #   #volumes:
  #   #  - ./service/template:/app
  #   #  - ./common:/app/common

  celery-worker:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_NAME=celery
    command: >
      celery -A main worker -l info -Q q_default
    env_file:
      - .env.dev
    environment:
      - SERVICE_NAME=celery
      - SERVICE_ID=celery.service
    volumes:
      - ./service/celery:/app
      - ./common:/app/common

  mcp:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_NAME=mcp
    command: ['python', 'main.py']
    env_file:
      - .env.dev
    environment:
      - SERVICE_NAME=mcp
      - SERVICE_ID=mcp.service
    volumes:
      - ./service/mcp:/app
      - ./common:/app/common

  template:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_NAME=template
    env_file:
      - .env.dev
    environment:
      - SERVICE_NAME=template
      - SERVICE_ID=template.service
    volumes:
      - ./service/template:/app
      - ./common:/app/common

networks:
  shared-net:
    name: net
