services:
  #nginx-ui-reverse-proxy:
  #  image: nginx
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - ./nginx/ui.conf:/etc/nginx/conf.d/default.conf
  #    - ./cert.pem:/etc/ssl/certs/cert.pem
  #    - ./key.pem:/etc/ssl/certs/key.pem

  gateway:
    build:
      context: src/service/gateway
      dockerfile: Dockerfile
      args:
        - SERVICE_DIR=hosts/multichat
    ports:
      - 80:80
      - 443:443

  host-multichat-ui:
    build:
      context: .
      # TODO dockerfile: docker/web/Dockerfile.dev
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=hosts/multichat
        - VITE_SERVICE_TYPE=ui
        - VITE_SERVICE_NAME=multichat
        - VITE_SERVICE_VERSION=v1
        - UI_DEPENDENCY_CHAT=http://ui.openschema.io/ui/v1/chat/remoteEntry.js
        - UI_DEPENDENCY_AUTH=http://ui.openschema.io/ui/v1/auth/remoteEntry.js
    env_file:
      - .env.dev
    environment:
      - VITE_SERVICE_TYPE=ui
      - VITE_SERVICE_NAME=multichat
      - VITE_SERVICE_VERSION=v1
      - VITE_SERVICE_ID=multichat.ui
      - VITE_SERVICE_DB_SCHEMA=multichat
    # TODO volumes:
    #  - ./src/web/apps/hosts/multichat:/app/apps/hosts/multichat

  remote-auth-ui:
    build:
      context: .
      # TODO dockerfile: docker/web/Dockerfile.dev
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=remotes/auth
    env_file:
      - .env.dev
    environment:
      - VITE_SERVICE_TYPE=ui
      - VITE_SERVICE_NAME=auth
      - VITE_SERVICE_VERSION=v1
      - VITE_SERVICE_ID=auth.ui
      - VITE_SERVICE_DB_SCHEMA=auth
    # TODO volumes:
    #  - ./src/web/apps/remotes/auth:/app/apps/remotes/auth

  remote-chat-ui:
    build:
      context: .
      # TODO dockerfile: docker/web/Dockerfile.dev
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=remotes/chat
        - VITE_SERVICE_TYPE=ui
        - VITE_SERVICE_NAME=chat
        - VITE_SERVICE_VERSION=v1
    env_file:
      - .env.dev
    environment:
      - VITE_SERVICE_TYPE=ui
      - VITE_SERVICE_NAME=chat
      - VITE_SERVICE_VERSION=v1
      - VITE_SERVICE_ID=chat.ui
      - VITE_SERVICE_DB_SCHEMA=chat
    # TODO volumes:
    #  - ./src/web/apps/remotes/chat:/app/apps/remotes/chat

networks:
  shared-net:
    name: net
