services:
  mcp:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_DIR=mcp
    env_file:
      - .env.dev
    command: ['python', 'main.py']
    environment:
      - SERVICE_TYPE=api
      - SERVICE_NAME=mcp
      - SERVICE_VERSION=v1
      - SERVICE_ID=mcp.api
      - SERVICE_DB_SCHEMA=mcp
    volumes:
      - ./src/service/mcp:/app
      - ./src/common:/app/common

  chat:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_DIR=chat
    env_file:
      - .env.dev
    environment:
      - SERVICE_TYPE=api
      - SERVICE_NAME=chat
      - SERVICE_VERSION=v1
      - SERVICE_ID=chat.api
      - SERVICE_DB_SCHEMA=chat
    volumes:
      - ./src/service/chat:/app
      - ./src/common:/app/common

  auth:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_DIR=auth
    env_file:
      - .env.dev
    environment:
      - SERVICE_TYPE=api
      - SERVICE_NAME=auth
      - SERVICE_VERSION=v1
      - SERVICE_ID=auth.api
      - SERVICE_DB_SCHEMA=auth
    volumes:
      - ./src/service/auth:/app
      - ./src/common:/app/common

  # template:
  #   build:
  #     context: .
  #     dockerfile: docker/python/Dockerfile.dev
  #     args:
  #       - SERVICE_DIR=template
  #   env_file:
  #     - .env.dev
  #   environment:
  #     - SERVICE_ID=template.service
  #     - SERVICE_NAME=template
  #     - SERVICE_VERSION=v1
  #     - SERVICE_DB_SCHEMA=template
  #   volumes:
  #     - ./src/service/template:/app
  #     - ./src/common:/app/common

  # template-celery:
  #   build:
  #     context: .
  #     dockerfile: docker/python/Dockerfile.dev
  #     args:
  #       - SERVICE_DIR=template
  #   env_file:
  #     - .env.dev
  #   command: >
  #     celery -A common.celery.worker worker -Q template --loglevel=info
  #   environment:
  #     - SERVICE_ID=template.service
  #     - SERVICE_NAME=template
  #     - SERVICE_VERSION=v1
  #     - SERVICE_DB_SCHEMA=template
  #   volumes:
  #     - ./src/service/template:/app
  #     - ./src/common:/app/common

networks:
  shared-net:
    name: net
