services:
  host-template:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=host/template
        - VITE_APP_OPENSCHEMA_UI_URL=http://ui.openschema.io
    environment:
      - VITE_APP_TODO=TODO

  remote-template:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=remote/template
    environment:
      - VITE_APP_TODO=TODO

networks:
  shared-net:
    name: net
