services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/certs/cert.pem
      - ./key.pem:/etc/ssl/certs/key.pem
    depends_on:
      # - template
      # - template-worker
      - auth
      - chat
      - conversation

  # template:
  #   build:
  #     context: .
  #     dockerfile: docker/python/Dockerfile.dev
  #     args:
  #       - SERVICE=template
  #   env_file:
  #     - .env.dev
  #   environment:
  #     - SERVICE_NAME=auth
  #     - SERVICE_ID=template.service
  #   volumes:
  #     - ./services/template:/app
  #     - ./common:/app/common

  # template-worker:
  #   build:
  #     context: .
  #     dockerfile: docker/python/Dockerfile.dev
  #     args:
  #       - SERVICE=template
  #   command: ["python", "worker.py"]
  #   env_file:
  #     - .env.dev
  #   environment:
  #     - SERVICE_NAME=auth
  #     - SERVICE_ID=template.service
  #   volumes:
  #     - ./services/template:/app
  #     - ./common:/app/common

  auth:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_NAME=auth
    env_file:
      - .env.dev
    environment:
      - SERVICE_NAME=auth
      - SERVICE_ID=auth.service
    volumes:
      - ./services/auth:/app
      - ./common:/app/common

  conversation:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_NAME=conversation
    env_file:
      - .env.dev
    environment:
      - SERVICE_NAME=conversation
      - SERVICE_ID=conversation.service
    volumes:
      - ./services/conversation:/app
      - ./common:/app/common

  chat:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE_NAME=chat
    env_file:
      - .env.dev
    environment:
      - SERVICE_NAME=chat
      - SERVICE_ID=chat.service
    volumes:
      - ./services/chat:/app
      - ./common:/app/common

networks:
  shared-net:
    name: net
