services:
  gateway:
    build:
      context: src/service/gateway
      dockerfile: Dockerfile
      args:
        - SERVICE_DIR=hosts/multichat
    ports:
      - 80:80
      - 443:443

  host-template:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=hosts/template
        - VITE_APP_OPENSCHEMA_UI_URL=http://ui.openschema.io
    environment:
      - VITE_APP_TODO=TODO

  remote-template:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - SERVICE_DIR=remotes/template
    environment:
      - VITE_APP_TODO=TODO

networks:
  shared-net:
    name: net
