FROM node:22-slim

ARG SERVICE_DIR
ARG BUILD_CONTEXT_PATH=src/web

WORKDIR /app

RUN corepack enable

COPY ${BUILD_CONTEXT_PATH}/pnpm-workspace.yaml ${BUILD_CONTEXT_PATH}/package.json ${BUILD_CONTEXT_PATH}/pnpm-lock.yaml ./
COPY ${BUILD_CONTEXT_PATH}/apps/${SERVICE_DIR}/package.json ./apps/${SERVICE_DIR}/package.json

RUN pnpm install --frozen-lockfile --filter ./apps/${SERVICE_DIR}...

WORKDIR /app/apps/${SERVICE_DIR}

EXPOSE 2000

CMD [ "pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "2000" ]