from celery import Celery
from common.config.const import (
    CELERY_RABBITMQ_HOST,
    CELERY_RABBITMQ_PASSWORD,
    CELERY_RABBITMQ_USER,
    CELERY_RABBITMQ_PORT,
    CELERY_RABBITMQ_VHOST,
)
from common.config.const import (
    CELERY_REDIS_HOST,
    CELERY_REDIS_PASSWORD,
    CELERY_REDIS_USER,
    CELERY_REDIS_PORT,
    CELERY_REDIS_DB,
)


BROKER_URL = f"amqp://{CELERY_RABBITMQ_USER}:{CELERY_RABBITMQ_PASSWORD}@{CELERY_RABBITMQ_HOST}:{CELERY_RABBITMQ_PORT}/{CELERY_RABBITMQ_VHOST}"
BACKEND_URL = f"redis://{CELERY_REDIS_USER}:{CELERY_REDIS_PASSWORD}@{CELERY_REDIS_HOST}:{CELERY_REDIS_PORT}/{CELERY_REDIS_DB}"


worker = Celery(
    "default",
    broker=BROKER_URL,
    backend=BACKEND_URL,
)
